## Deliverable 2. Create a Customer Travel Destinations Map.

In [11]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps


# Import the API key.
from config import weather_api_key



# Import API key
from config import g_key
# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Description
0,0,Cherskiy,68.75,161.30,37.24,94,100,22.57,RU,2020-08-22 20:56:17,light rain
1,1,Jamestown,42.10,-79.24,82.99,51,75,4.70,US,2020-08-22 20:56:00,broken clouds
2,2,Cururupu,-1.83,-44.87,78.44,83,9,3.62,BR,2020-08-22 20:56:17,clear sky
3,3,Ahipara,-35.17,173.17,58.32,87,25,8.30,NZ,2020-08-22 20:56:17,scattered clouds
4,4,Ushuaia,-54.80,-68.30,44.60,77,40,16.11,AR,2020-08-22 20:55:16,shower rain

In [12]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
#653
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [13]:
#653
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Description
1,1,Jamestown,42.10,-79.24,82.99,51,75,4.70,US,2020-08-22 20:56:00,broken clouds
2,2,Cururupu,-1.83,-44.87,78.44,83,9,3.62,BR,2020-08-22 20:56:17,clear sky
6,6,San Patricio,19.22,-104.70,89.60,75,75,11.41,MX,2020-08-22 20:56:18,broken clouds
12,12,Pacific Grove,36.62,-121.92,84.99,64,75,5.82,US,2020-08-22 20:45:27,haze
13,13,Butaritari,3.07,172.79,82.90,63,100,6.58,KI,2020-08-22 20:56:19,overcast clouds
14,14,Albany,42.60,-73.97,84.00,46,0,8.16,US,2020-08-22 20:55:34,clear sky
16,16,Rudbar,30.15,62.60,84.52,14,0,8.61,AF,2020-08-22 20:56:20,clear sky
23,23,Atuona,-9.80,-139.03,78.21,78,41,18.25,PF,2020-08-22 20:56:22,light rain
26,26,Dingle,11.00,122.67,76.86,88,100,1.88,PH,2020-08-22 20:56:22,overcast clouds
27,27,Jiquipilas,16.67,-93.65,86.00,58,75,2.24,MX,2020-08-22 20:56:23,broken clouds

In [14]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID        373
City           373
Lat            373
Lng            373
Max Temp       373
Humidity       373
Cloudiness     373
Wind Speed     373
Country        373
Date           187
Description    373
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [18]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

NameError: name 'clean_df' is not defined

In [17]:
#654
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    
    
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

    # 6c. Get latitude and longitude from DataFrame

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    
    
    # Starting URL for Weather Map API Call.
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key
print(url)

# Get the JSON text of the 'Get' request.
city_weather.json()
    
    

    # 6e. Make request and retrieve the JSON data from the search. 
    
    # Make a 'Get' request for the city weather.
city_weather = requests.get(city_url)
city_weather


   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
    # Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    
    
    # Grab the first hotel from the results and store the name.
try:
hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
except (IndexError):
print("Hotel not found... skipping.")

IndentationError: expected an indented block (<ipython-input-17-0dc5691f3647>, line 57)

In [ ]:
# 7. Drop the rows where there is no Hotel Name.

In [ ]:
# 8a. Create the output File (CSV)

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [ ]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure